//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobLang.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobLang.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data Heap a
        ///	case Empty
        ///	case Heap of a (List (Heap a))
        ///
        ///def heap_link lhs rhs as
        ///	match (lhs, rhs)
        ///		with (Empty, rhs) then rhs
        ///		with (lhs, Empty) then lhs
        ///		with ((Heap lhsval lhschld), (Heap rhsval rhschld)) if lhsval &lt; rhsval then
        ///			Heap lhsval (rhs :: lhschld)
        ///		with ((Heap lhsval lhschld), (Heap rhsval rhschld)) then
        ///			Heap rhsval (lhs :: rhschld)
        ///
        ///def heap_merge list as
        ///	match list
        ///		with Nil then Empty
        ///		with Cons heap Nil then heap
        ///		with Cons h1 (Cons h2 hs) then heap_link (hea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataStructures {
            get {
                return ResourceManager.GetString("DataStructures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string Program_Execute_Error {
            get {
                return ResourceManager.GetString("Program_Execute_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to result : {1} = {0}.
        /// </summary>
        internal static string Program_Execute_Result {
            get {
                return ResourceManager.GetString("Program_Execute_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to def operator $ f x as f x
        ///
        ///def operator @ f g x as f (g x)
        ///
        ///def flip f x y as f y x
        ///
        ///def fst (x, _) as x
        ///
        ///def snd (_, x) as x
        ///
        ///data List a
        ///	case Nil
        ///	case Cons of a (List a)
        ///
        ///def operator :: x as Cons x
        ///
        ///def head (Cons x _) as x
        ///
        ///def tail (Cons _ x) as x
        ///
        ///def flip f x y as f y x
        ///
        ///def map f list as
        ///	match list
        ///		with Nil then Nil 
        ///		with Cons x xs then f x :: map f xs
        ///
        ///def foldl f initial list as
        ///	match list
        ///		with Nil then initial
        ///		with Cons x xs then foldl f (f initial x) xs        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StdLib {
            get {
                return ResourceManager.GetString("StdLib", resourceCulture);
            }
        }
    }
}
